
import './globals.css'
import { Inter } from 'next/font/google'
import { UserProvider } from '@auth0/nextjs-auth0/client';
import { CartProvider } from '../providers/cartProvider';

//components
import NavBar from './components/navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Five Star Souvenirs',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
        <UserProvider>
          
          <body className={inter.className}>
          <CartProvider>
            <NavBar/>
            {children}
          </CartProvider>
            </body>
          
        </UserProvider>
      
      
    </html>
  )
}
